network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      addresses:
        - 192.168.100.2/24
      nameservers:
        addresses:
          - 9.9.9.9
      routes:
        - to: default
          via: 192.168.100.1
