[Distribution]
Distribution=ubuntu
Release=noble
Repositories=main restricted universe multiverse

[Output]
Format=disk
Output=tinfoilcvm

[Content]
Hostname=ubuntu-cvm
Bootable=yes
RootPassword=helloworld
KernelCommandLine=console=ttyS0
PackageDirectories=guest
Packages=
    systemd
    linux-image-generic
    efibootmgr
    console-setup
    openssh-server
    ubuntu-standard
    grub-efi-amd64
VolatilePackages=
    linux-headers-6.10.0-snp-guest-0c3836482481
    linux-image-6.10.0-snp-guest-0c3836482481
    linux-image-6.10.0-snp-guest-0c3836482481-dbg

[Build]
ToolsTree=default
