name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: large
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v4

      - name: Install mkosi
        run: |
          apt install -y pipx
          pipx install git+https://github.com/systemd/mkosi.git

      - name: Build image
        run: |
            mkosi --image-version ${{ github.ref }}
